version: "3.8"

services:
  app:
    build: .
    ports:
      - 80:8000
    environment:
      # connection via `dialect+driver://username:password@host[:port]/database`
      # POSTGRES_PASSWORD is read from .env
      DATABASE_URL: postgresql+psycopg2://vp:${POSTGRES_PASSWORD}@db/vp
    restart: unless-stopped

  db:
    image: postgres:16.2-alpine3.19
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # from .env
      POSTGRES_DB: vp
      POSTGRES_USER: vp
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/vp.sql
    restart: unless-stopped

    # uncomment for lcoal dev
    # ports:
    #   - 5432:5432
