version: "3.8"

services:
  app:
    image: tomjtoth/veripalvelu
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./.env:/usr/src/app/.env
    restart: unless-stopped

  db:
    image: postgres:16.2-alpine3.19
    environment:
       # all 3 are set in .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/vp.sql
    restart: unless-stopped

    # uncomment for local dev
    # ports:
    #   - 5432:5432
