name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]    
    types: [opened, synchronize]
    
env:
  DEPLOY: ${{ !contains(github.event.head_commit.message, '#skip') && github.event_name == 'push' }}

jobs:
  lint_build_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: python3 -m venv venv
      - run: pip install -r requirements.txt
      - run: pip install pylint

      # to be implemneted, for now it's only a placeholder
      # - name: Analysing the code with pylint
      #   run: pylint $(git ls-files '*.py')
      

  docker:
    # if: ${{ github.env.DEPLOY == 'true' }}
    runs-on: ubuntu-latest
    needs: [lint_build_test]
    steps:
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      # - name: Checkout
      #   uses: actions/checkout@v4
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: tomjtoth/veripalvelu

      # - name: report success
      #   if: success()
      #   uses: rjstone/discord-webhook-notify@v1
      #   with:
      #     severity: info
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    
      # - name: report failure
      #   if: failure()
      #   uses: rjstone/discord-webhook-notify@v1
      #   with:
      #     severity: error
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      