name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-latest-arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Checkout to the repository
      - uses: actions/checkout@v2

      # We need to login so we can later push the image without issues.
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Builds devopsdockeruh/docker-hy.github.io
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "tomjtoth/veripalvelu:latest-${{ if eq(matrix.os, 'ubuntu-latest-arm64') }}arm64{{ else }}amd64{{ endif }}"
          