name: Release

on:
  push:
    branches:
      - main
env:
  DOCKER: ${{ !contains(github.event.head_commit.message, '#skip') && github.event_name == 'push' }}
      
jobs:
  linting:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: python3 -m venv venv
      - run: pip install -r requirements.txt
      - run: pip install pylint
      - name: Analysing the code with pylint
        run: pylint $(git ls-files '*.py')

  docker:
    if: ${{ github.env.DOCKER == 'true' }}
    runs-on: ubuntu-latest
    needs: [linting]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tomjtoth/veripalvelu
